### ISSUE TITLE
在锁屏下推送通知图标显示异常

### ISSUE THREAD

**Issue by SixGo** [chanify/chanify-ios#105]
您好，我遇到一个问题我在锁屏状态下推送通知，锁屏界面图标显示异常，主屏幕上是正常的。我图标配置的是显示频道图标 ios 版本号是15.
![WechatIMG15](https://user-images.githubusercontent.com/20434885/161566625-8bdcc0da-0c6f-41c6-8c7c-40ea7273aa43.jpeg)
4

**Comment by wizjin** [comment]
你好，请问是手机重启后没有输入过密码，然后遇到的吗？

chanify采用的是重启后第一次解锁后才能使用的加密模式。加密的时候chnaify是读不到用户保存的数据。所以可能会出现截图中的问题。

还有问题欢迎随时联系。

谢谢

**Comment by SixGo** [comment]
> 

不是重启后的首次推送，前面两次是我锁屏后立即发送的，后面两次是锁屏几秒后在发的。我试过重启设备仍然有这个问题。

**Comment by wizjin** [comment]
好的，谢谢反馈。我晚点看一下为什么。
