### ISSUE TITLE
Mac 端不会弹出消息通知

### ISSUE THREAD

**Issue by Xm798** [chanify/chanify-ios#106]
如题，Mac端收到消息时，通知中心不会弹出提醒，只有当APP运行且图标常驻Dock时有小红点提示。

相关权限已授予。

**Comment by wizjin** [comment]
Mac 端目前由于苹果的API限制，只有运行时才会接收消息，离线时暂时收不到消息。

**Comment by Xm798** [comment]
> Mac 端目前由于苹果的API限制，只有运行时才会接收消息，离线时暂时收不到消息。

但我运行时只能收到小红点提示，无法弹出通知提醒，这个是正常的吗

**Comment by wizjin** [comment]
是的，目前MacOS版本的功能就是这样的，通知中心的相关功能还没来得及开发。十分抱歉。

**Comment by Xm798** [comment]
> 是的，目前MacOS版本的功能就是这样的，通知中心的相关功能还没来得及开发。十分抱歉。

明白了，谢谢～期待功能能够完善！
