### ISSUE TITLE
中国地区速度很慢哦，发一条消息耗时1秒钟差不多，能不能改善下。愿意提供少量服务器流量赞助

### ISSUE THREAD

**Issue by johnxiongs** [chanify/chanify-ios#28]
中国地区速度很慢哦，发一条消息耗时1秒钟差不多，能不能改善下。愿意提供少量服务器流量赞助

**Comment by wizjin** [comment]
你好，能方便说一下你在什么地区发送的，使用什么工具发送的，是如何测得需要 1 秒时间的吗？我试了一下， 用 curl 在上海 40ms 就可以发送成功了。

目前只对发送频率稍为限制了一下，一般不会影响发送耗时的，如果实在对发送响应时间有要求建议可以自建服务器。

**Comment by johnxiongs** [comment]
> 你好，能方便说一下你在什么地区发送的，使用什么工具发送的，是如何测得需要 1 秒时间的吗？我试了一下， 用 curl 在上海 40ms 就可以发送成功了。
> 
> 目前只对发送频率稍为限制了一下，一般不会影响发送耗时的，如果实在对发送响应时间有要求建议可以自建服务器。

我在深圳用python代码测试的
```
import time
from urllib import request, parse

data = parse.urlencode({'text': 'hello'}).encode()
token = 'token'
req = request.Request(f"https://api.chanify.net/v1/sender/{token}", data=data)
while 1:
    s = time.time()
    request.urlopen(req)
    e = time.time()
    print(e - s)

```
运行结果都是在0.5秒左右，如截图
![image](https://user-images.githubusercontent.com/37213061/119070382-77fe4280-ba1a-11eb-8179-1c1c9e6b95e6.png)

**Comment by wizjin** [comment]
你好，我用你给的代码测试了一下基本上也是 0.5s 左右，大致看了一下主要时间花在建立链接上了。

十分抱歉，如果不迁移服务器的话，短期内没有比较好的方案可以解决的这个问题，如果需要大量并发的话建议还是自建服务器比较好。

PS: 可以的话请不要用死循环测试，容易被服务器误认为 ddos。:)

**Comment by johnxiongs** [comment]
> 你好，我用你给的代码测试了一下基本上也是 0.5s 左右，大致看了一下主要时间花在建立链接上了。
> 
> 十分抱歉，如果不迁移服务器的话，短期内没有比较好的方案可以解决的这个问题，如果需要大量并发的话建议还是自建服务器比较好。
> 
> PS: 可以的话请不要用死循环测试，容易被服务器误认为 ddos。:)

死循环只是临时测试用一下，自建服务器麻烦吗？不太懂啊

**Comment by wizjin** [comment]
自建服务器不是很麻烦，可以参看靠 [这里](https://github.com/chanify/chanify/blob/main/README-zh_CN.md#%E4%BD%9C%E4%B8%BA%E6%9C%89%E7%8A%B6%E6%80%81%E6%9C%8D%E5%8A%A1%E5%99%A8)

如果有服务器可以部署 docker 的会更简单一些。

有问题欢迎随时交流。

**Comment by johnxiongs** [comment]
> 自建服务器不是很麻烦，可以参看靠 [这里](https://github.com/chanify/chanify/blob/main/README-zh_CN.md#%E4%BD%9C%E4%B8%BA%E6%9C%89%E7%8A%B6%E6%80%81%E6%9C%8D%E5%8A%A1%E5%99%A8)
> 
> 如果有服务器可以部署 docker 的会更简单一些。
> 
> 有问题欢迎随时交流。

有微信群交流不

**Comment by wizjin** [comment]
抱歉，微信群还没建，回头我抽空建一个吧。

**Comment by johnxiongs** [comment]
> 抱歉，微信群还没建，回头我抽空建一个吧。

好的，谢谢大佬，等你微信群

**Comment by wizjin** [comment]
@johnsxiong 抽空建了一个 QQ 群，https://github.com/chanify/chanify/issues/105
