### ISSUE TITLE
无法运行，报错Command RuleScriptExecution failed with a nonzero exit code希望作者大神看看

### ISSUE THREAD

**Issue by huoxingdeguoguo** [chanify/chanify-ios#36]
下载的demo，运行时报错，不知道怎么解决，下面是截图，希望大神给看看![image](https://user-images.githubusercontent.com/13297012/120953183-0eeb2e80-c77f-11eb-8e98-fbbc449961b1.png)

**Comment by wizjin** [comment]
需要安装 protobuf，可以使用 brew。

```bash
brew install protobuf
```

**Comment by huoxingdeguoguo** [comment]
> 需要安装 protobuf，可以使用 brew。
> 
> ```shell
> brew install protobuf
> ```

嗯嗯，我试试，谢谢了

**Comment by huoxingdeguoguo** [comment]
已经解决，谢谢指点
