### ISSUE TITLE
Make "Uncategorized" channel *REAL* uncategorized

### ISSUE THREAD

**Issue by lgxz** [chanify/chanify-ios#46]
The so-called "Uncategorised" channel is indeed a *NORMAL* channel and has it's own Token.

I modified the server code to send message with uid instead of the channel token.  for example,
`https://test.server/v2/sender/:uid/:msg`

Then the funny thing is:
1. The message **DOES** pop up in the notification center.
2. Chanify App shows the number of unread messages.
3. You can't see the message in App because  it doesn't belong to any channel.

[Screenshot](https://pasteboard.co/KfpsWdp.png)

**Comment by lgxz** [comment]
> @lgxz Avoid illegal channels that have been used, so the uncategorized channel is the default channel.
> 
> If you modified the server code, you can add default channel for uid.
> 
> Thanks

Yes. The problem is that the messages will be invisible in App completely.  The App only shows the number of unread messages.  And, you can't get rid of the unread number from App forever.

**Comment by wizjin** [comment]
Server will add default channel.

https://github.com/chanify/chanify/blob/e251ca1c307b6414c0978273d0b74e14706121ba/model/token.go#L64

How did you modify the code?

Thanks.

**Comment by lgxz** [comment]
> Server will add default channel.
> 
> https://github.com/chanify/chanify/blob/e251ca1c307b6414c0978273d0b74e14706121ba/model/token.go#L64
> 
> How did you modify the code?
> 
> Thanks.

I finished the change in 15 minutes. So it's just for test purpose:

`
diff --git a/core/core.go b/core/core.go
index 478f2f4..b216798 100644
--- a/core/core.go
+++ b/core/core.go
@@ -65,6 +65,9 @@ func (c *Core) APIHandler() http.Handler {
 	s.POST("/sender/*token", c.handlePostSender)
 	s.POST("/sender", c.handlePostSender)
 
+	s = r.Group("/v2")
+	s.GET("/sender/:uid/:msg", c.handleUserSender)
+
 	api := r.Group("/rest/v1")
 	api.GET("/info", c.handleInfo)
 	api.GET("/qrcode", c.handleQRCode)
diff --git a/core/sender.go b/core/sender.go
index 6317610..3e283ce 100644
--- a/core/sender.go
+++ b/core/sender.go
@@ -31,6 +31,26 @@ func (c *Core) handleSender(ctx *gin.Context) {
 	c.sendMsg(ctx, token, msg.SoundName(ctx.Query("sound")).SetPriority(parsePriority(ctx.Query("priority"))))
 }
 
+func (c *Core) handleUserSender(ctx *gin.Context) {
+	uid, err := c.getUid(ctx)
+	if len(uid) == 0 {
+		ctx.JSON(http.StatusUnauthorized, gin.H{"res": http.StatusUnauthorized, "msg": "invalid user id"})
+		return
+	}
+	text := ctx.Param("msg")
+	if len(text) <= 0 {
+		ctx.JSON(http.StatusBadRequest, gin.H{"res": http.StatusNoContent, "msg": "no message content"})
+		return
+	}
+	msg := &model.Message{}
+	msg, err = c.makeTextContent(msg, text, ctx.Query("title"), ctx.Query("copy"), ctx.Query("autocopy"), ctx.QueryArray("action"))
+	if err != nil {
+		ctx.JSON(http.StatusRequestEntityTooLarge, gin.H{"res": http.StatusRequestEntityTooLarge, "msg": "too large text content"})
+		return
+	}
+	c.sendUidMsg(ctx, uid, msg.SoundName(ctx.Query("sound")).SetPriority(parsePriority(ctx.Query("priority"))))
+}
+
 func (c *Core) handlePostSender(ctx *gin.Context) {
 	params := &MsgParam{}
 	params.Token, _ = c.getToken(ctx)
@@ -86,6 +106,30 @@ func (c *Core) handlePostSender(ctx *gin.Context) {
 	c.sendMsg(ctx, params.Token, msg.SoundName(params.Sound).SetPriority(params.Priority))
 }
 
+func (c *Core) sendUidDirect(ctx *gin.Context, uid string, msg *model.Message) {
+	key, err := c.logic.GetUserKey(uid)
+	if err != nil {
+		ctx.JSON(http.StatusBadRequest, gin.H{"res": http.StatusBadRequest, "msg": "invalid user"})
+		return
+	}
+	devs, err := c.logic.GetDevices(uid)
+	if err != nil || len(devs) <= 0 {
+		ctx.JSON(http.StatusNotFound, gin.H{"res": http.StatusNotFound, "msg": "no devices found"})
+		return
+	}
+	out := msg.EncryptData(key, uint64(time.Now().UTC().UnixNano()))
+	if len(out) > 4000 {
+		ctx.JSON(http.StatusRequestEntityTooLarge, gin.H{"res": http.StatusRequestEntityTooLarge, "msg": "message body too large"})
+		return
+	}
+	uuid, n := c.logic.SendAPNS(uid, out, devs, int(msg.Priority))
+	if n <= 0 {
+		ctx.JSON(http.StatusNotFound, gin.H{"res": http.StatusNotFound, "msg": "no devices send success"})
+		return
+	}
+	ctx.JSON(http.StatusOK, gin.H{"request-uid": uuid})
+}
+
 func (c *Core) sendDirect(ctx *gin.Context, token *model.Token, msg *model.Message) {
 	uid := token.GetUserID()
 	key, err := c.logic.GetUserKey(uid)
@@ -129,6 +173,18 @@ func (c *Core) sendForward(ctx *gin.Context, token *model.Token, msg *model.Mess
 	ctx.DataFromReader(resp.StatusCode, resp.ContentLength, resp.Header.Get("Content-Type"), reader, map[string]string{})
 }
 
+func (c *Core) sendUidMsg(ctx *gin.Context, uid string, msg *model.Message) {
+	u, err := c.logic.GetUser(uid)
+	if err != nil {
+		ctx.JSON(http.StatusBadRequest, gin.H{"res": http.StatusBadRequest, "msg": "invalid user"})
+		return
+	}
+	if u.IsServerless() {
+		return
+	}
+	c.sendUidDirect(ctx, uid, msg)
+}
+
 func (c *Core) sendMsg(ctx *gin.Context, token *model.Token, msg *model.Message) {
 	u, err := c.logic.GetUser(token.GetUserID())
 	if err != nil {
diff --git a/core/utils.go b/core/utils.go
index 859a58d..5f13714 100644
--- a/core/utils.go
+++ b/core/utils.go
@@ -63,6 +63,20 @@ func verifySign(key string, sign []byte, data []byte) bool {
 	return pk.Verify(data, sign)
 }
 
+func (c *Core) getUid(ctx *gin.Context) (string, error) {
+	token := ctx.GetHeader("uid")
+	if len(token) <= 0 {
+		token = ctx.Query("uid")
+		if len(token) <= 0 {
+			token = ctx.Param("uid")
+			if len(token) > 0 && token[0] == '/' {
+				token = token[1:]
+			}
+		}
+	}
+	return token, nil
+}
+
 func (c *Core) getToken(ctx *gin.Context) (*model.Token, error) {
 	token := ctx.GetHeader("token")
 	if len(token) <= 0 {
`

**Comment by lgxz** [comment]
> Server will add default channel.
> 
> https://github.com/chanify/chanify/blob/e251ca1c307b6414c0978273d0b74e14706121ba/model/token.go#L64
> 
> How did you modify the code?
> 
> Thanks.

Great. Sorry, I don't know how to paste formatted code.
It's very simple:
1. Add s.GET("/sender/:uid/:msg", c.handleUserSender)
2. In handleUserSender, extract uid from request instead of token. And change msg to msg := &model.Message{}
3. In handleUserSender, call c.sendUidMsg(ctx, uid, msg.SoundName(ctx.Query("sound")).SetPriority(parsePriority(ctx.Query("priority"))))
4. Copy sendMsg to sendUidMsg, change token to uid

**Comment by lgxz** [comment]
> Server will add default channel.
> 
> https://github.com/chanify/chanify/blob/e251ca1c307b6414c0978273d0b74e14706121ba/model/token.go#L64
> 
> How did you modify the code?
> 
> Thanks.

Ok. Here is the commits:

https://github.com/lgxz/chanify/commit/002f2066e7ad02a91cb914a15c841ece304d235a

**Comment by wizjin** [comment]
```go
m := &Message{}
m.From = tk.GetNodeID()
m.Channel = tk.GetChannel()
m.TokenHash = tk.HashValue()
```

`From`, `Channel` and `TokenHash` must be inited, then client will work.

- From: NodeId for decrypt message
- Channel: Can use `defaultChannel `
- TokenHash: Use for feature(token blocked list). You can use empty string `""`, but this way will disable token blocked list.

Thanks

**Comment by lgxz** [comment]
> ```go
> ```go
> m := &Message{}
> m.From = tk.GetNodeID()
> m.Channel = tk.GetChannel()
> m.TokenHash = tk.HashValue()
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> From, Channel and TokenHash must be inited, then client will work.
> 
> From: NodeId for decrypt message
> Channel: Can use defaultChannel 
> TokenHash: Use for feature(token blocked list). You can use empty string "", but this way will disable token blocked list.
> 
> Thanks
> ```

Thanks.  

The message can be displayed in iOS Notification Center correctly even without the From field.
Does the current App support default channel? I will try it.

**Comment by wizjin** [comment]
Without the `From` field work, because SendAPNS will fix it. (only direct send can ignore `From` field)

You can add defaultChannel, then client will work.

**Comment by lgxz** [comment]
> Without the `From` field work, because SendAPNS will fix it. (only direct send can ignore `From` field)
> 
> You can add defaultChannel, then client will work.

Thanks.

Just tried it, same result.  The messages are still invisible  in App.

**Comment by wizjin** [comment]
I suggest you to set `msg.From` with `logic.NodeID`, because the `image/sound/file/long text` message need `msg.From`.

The [`feature 82`](https://github.com/chanify/chanify/issues/82) will can be used to solve the empty channel.

- if `m.Channel == nil`, client will set channel to defaultChannel
- if `m.Channel == invalid channel`, client will ignore this channel

Thanks

**Comment by lgxz** [comment]
> ```go
> ```go
> m := &Message{}
> m.From = tk.GetNodeID()
> m.Channel = tk.GetChannel()
> m.TokenHash = tk.HashValue()
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> From, Channel and TokenHash must be inited, then client will work.
> 
> From: NodeId for decrypt message
> Channel: Can use defaultChannel 
> TokenHash: Use for feature(token blocked list). You can use empty string "", but this way will disable token blocked list.
> 
> Thanks
> ```

The defaultChannel is an unnamed system channel.  Messages sent to the defaultChannel will be put in the uncategorised channel by client app.

But,  if you set the "Name" property of defaultChannel, this will force client app create an unnamed system channel. 
And, user can't delete the new created channel.


> I suggest you to set `msg.From` with `logic.NodeID`, because the `image/sound/file/long text` message need `msg.From`.
> 
> The [`feature 47`](https://github.com/chanify/chanify-ios/issues/47) will can be used to solve the empty channel.
> 
> * if `m.Channel == nil`, client will set channel to defaultChannel
> * if `m.Channel == invalid channel`, client will ignore this channel
> 
> Thanks

Thanks.

What is an "invalid channel"?
I hope that client won't ignore the unknown channels so that we can push categorized messages to many clients without knowing every channel token.

**Comment by lgxz** [comment]
This is the commit to send categorised message to user directly:
https://github.com/lgxz/chanify/commit/a4f6f526d5758654bd8fa8c95515769f6ca113aa

We do not need know the channel token of every client.  

By "curl https://server/.../msg?chan=Event&code=100", the client will create "Event" channel automatically and put message in it.

**Comment by wizjin** [comment]
v1.2.2 release
