### ISSUE TITLE
推送预览显示消息内容很重要啊，为啥不显示啊

### ISSUE THREAD

**Issue by thelostpeace** [chanify/chanify-ios#48]
推送预览显示消息内容很重要啊，为啥不显示啊。如果预览只是显示`收到了一条消息`，那这个通知还有啥意义呢，还是得打开app去看。`chanify`支持图片和文件真是太棒了，我目前用的邮件通知，希望`chanity`能支持这个feature。:-)

**Comment by wizjin** [comment]
你好，请问是什么消息只显示收到了一条消息？可以试试重启手机或者重新添加节点服务器。

正常情况文本消息是会显示消息内容的。

**Comment by thelostpeace** [comment]
@wizjin 重启后可以正常显示了，感谢&感恩～
