### ISSUE TITLE
有没有可能支持Android？

### ISSUE THREAD

**Issue by CrazyMelody** [chanify/chanify-ios#50]
无意发现的宝藏APP，不懂移动端，好奇问下有没有可能支持Android？貌似都没发现这类通知APP有支持android的

另外作者啥时候搞个微信群？

**Comment by wizjin** [comment]
你好，很高兴你能喜欢这个 App，Android 暂时没有比较好的方案，google 的推送不是所有区域能用，各家手机厂家自己的推送比较杂。十分抱歉了。

微信群暂时还没空弄。

**Comment by CrazyMelody** [comment]
了解了，感谢
