### ISSUE TITLE
feat:可不可以支持消息、图片、文件的全选删除

### ISSUE THREAD

**Issue by thelostpeace** [chanify/chanify-ios#58]
每天收取的消息量、文件量和图片量有点大，时间一久感觉内存会吃不消，希望可以支持以上功能，不甚感激。:-)

**Comment by wizjin** [comment]
你好，消息的话在消息列表页面，长按左上角的按钮有清除制定 channel 所有消息的功能。

图片和文件的清除后面的版本就会添加。

谢谢你的建议

**Comment by thelostpeace** [comment]
> 你好，消息的话在消息列表页面，长按左上角的按钮有清除制定 channel 所有消息的功能。
> 
> 图片和文件的清除后面的版本就会添加。
> 
> 谢谢你的建议

左上角是返回，还是我理解错了呀……可以帮忙截个图么

**Comment by wizjin** [comment]
抱歉，是我说错了，是右上角。单击会进入频道详情，长按会出菜单，里面有清除消息。

**Comment by wizjin** [comment]
See https://github.com/chanify/chanify-ios/issues/59
